// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;

public static class ListExtensions
{
	public static void AddMany<T>(this List<T> list, params T[] elements)
	{
		for (int i = 0; i < elements.Length; i++)
		{
			list.Add(elements[i]);
		}
	}
}