/*
    ================================================================================
    Copyright Centre National de la Recherche Scientifique (CNRS)
        Contributors and copyright holders :

        Xavier Martinez, 2017-2021
        Marc Baaden, 2010-2021
        baaden@smplinux.de
        http://www.baaden.ibpc.fr

        This software is a computer program based on the Unity3D game engine.
        It is part of UnityMol, a general framework whose purpose is to provide
        a prototype for developing molecular graphics and scientific
        visualisation applications. More details about UnityMol are provided at
        the following URL: "http://unitymol.sourceforge.net". Parts of this
        source code are heavily inspired from the advice provided on the Unity3D
        forums and the Internet.

        This program is free software: you can redistribute it and/or modify
        it under the terms of the GNU General Public License as published by
        the Free Software Foundation, either version 3 of the License, or
        (at your option) any later version.

        This program is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU General Public License for more details.

        You should have received a copy of the GNU General Public License
        along with this program. If not, see <https://www.gnu.org/licenses/>.

        References : 
        If you use this code, please cite the following reference :         
        Z. Lv, A. Tek, F. Da Silva, C. Empereur-mot, M. Chavent and M. Baaden:
        "Game on, Science - how video game technology may help biologists tackle
        visualization challenges" (2013), PLoS ONE 8(3):e57990.
        doi:10.1371/journal.pone.0057990
       
        If you use the HyperBalls visualization metaphor, please also cite the
        following reference : M. Chavent, A. Vanel, A. Tek, B. Levy, S. Robert,
        B. Raffin and M. Baaden: "GPU-accelerated atom and dynamic bond visualization
        using HyperBalls, a unified algorithm for balls, sticks and hyperboloids",
        J. Comput. Chem., 2011, 32, 2924

    Please contact unitymol@gmail.com
    ================================================================================
*/


using UnityEngine;
using VRTK;
using System.Collections;

[RequireComponent(typeof(VRTK_InteractableObject))]
public class OnControllerGrabExtension : MonoBehaviour {
    // this script demonstrates how to detect when this object has been grabbed by a controller.  
    // it requires the object already have the VRTK_InteractableObject attached.  
    // it simpley subscribes to the event generated by the interactable object script.  
    // there are many more events to subscribe to so lots of interaction options are posible. 

    // use this script to ADD functionality to your object not provied by the VRTK scripts.
    // this could include triggering other actions based, etc. 
    // a full list of events can be found in the interactable object script.

    Transform collidersT;

    Transform savedParent;


    // Use this for initialization
    void Start ()
    {

        //make sure the object has the VRTK script attached... 
        if (GetComponent<VRTK_InteractableObject>() == null)
        {
            Debug.LogError("OnControllerGrabExtension is required to be attached to an Object that has the VRTK_InteractableObject script attached to it");
            return;
        }

        //subscribe to the event.  NOTE: the "ObectGrabbed"  this is the procedure to invoke if this objectis grabbed.. 
        GetComponent<VRTK_InteractableObject>().InteractableObjectGrabbed += new InteractableObjectEventHandler(ObjectGrabbed);
        GetComponent<VRTK_InteractableObject>().InteractableObjectUngrabbed += new InteractableObjectEventHandler(ObjectUngrabbed);

        collidersT = transform.Find("Colliders");
        if(collidersT != null){
            savedParent = collidersT.parent;
        }


    }

    //this object has been grabbed.. so do what ever is in the code.. 
    private void ObjectGrabbed(object sender, InteractableObjectEventArgs e)
    {
        if(collidersT != null){
            // collidersT.parent = null;
            // collidersT.gameObject.SetActive(false);
        }
    }

    private void ObjectUngrabbed(object send, InteractableObjectEventArgs e){
        if(collidersT != null){
            // collidersT.gameObject.SetActive(true);
            // collidersT.parent = savedParent;
            // collidersT.localPosition = Vector3.zero;
            // collidersT.localScale = Vector3.one;
            // collidersT.localRotation = Quaternion.identity;
        }
    }
}
